@startuml
title Tour Operator Bounded Context Overview

top to bottom direction
skinparam shadowing false
skinparam packageStyle rectangle
skinparam package {
  BackgroundColor White
  BorderColor #334155
  FontColor #0F172A
}
package "Christopher Columbus Travel" <<enterprise>> {
  package "Interaction" <<layer>> {
    package "Customer Interaction" <<bounded context>>
    package "Staff Interaction" <<bounded context>>
    package "Supplier Interaction" <<bounded context>>

    "Customer Interaction" -[hidden]right- "Staff Interaction"
    "Staff Interaction" -[hidden]right- "Supplier Interaction"
  }

  package "Core Business" <<layer>> {
    package "Travel Product Design" <<bounded context>>
    package "Procurement" <<bounded context>>
    package "Sales" <<bounded context>>
    package "Travel Execution" <<bounded context>>

    "Travel Product Design" -[hidden]right- "Procurement"
    "Procurement" -[hidden]right- "Sales"
    "Sales" -[hidden]right- "Travel Execution"
  }

  package "Resources" <<layer>> {
    package "Customer Management" <<bounded context>>
    package "Travel Product Management" <<bounded context>>
    package "Order Management" <<bounded context>>

    "Customer Management" -[hidden]right- "Travel Product Management"
    "Travel Product Management" -[hidden]right- "Order Management"
  }

  package "Supporting Processes" <<layer>> {
    package "Accounting" <<bounded context>>
    package "Reporting" <<bounded context>>
    package "Human Resources" <<bounded context>>

    "Accounting" -[hidden]right- "Reporting"
    "Reporting" -[hidden]right- "Human Resources"
  }

  "Customer Interaction" -[hidden]down- "Travel Product Design"
  "Staff Interaction" -[hidden]down- "Procurement"
  "Supplier Interaction" -[hidden]down- "Travel Execution"

  "Travel Product Design" -[hidden]down- "Customer Management"
  "Procurement" -[hidden]down- "Travel Product Management"
  "Travel Execution" -[hidden]down- "Order Management"

  "Customer Management" -[hidden]down- "Accounting"
  "Travel Product Management" -[hidden]down- "Reporting"
  "Order Management" -[hidden]down- "Human Resources"
}

@enduml
